### PR TITLE
OIDC login

### LINKED ISSUE #2064: OIDC login
Add login support for OIDC via identity.wekit-ecs.com (KeyCloak)

### PR DESCRIPTION
**Pull request by fwild**
OIDC with https://identity.wekit-ecs.com works, stores the token locally and retrieves it instead of logging in again when opening the app next time. The logout button in profile also properly logs out and removes the stored token from config.info. User Info is retrieved from the endpoint.

Resolves #2064

### CODE REVIEW

**Comment by fwild** [comment]
https://github.com/user-attachments/assets/024fb5c6-8269-41eb-8fb4-1412b51de334

**Comment by fwild** [comment]
https://github.com/user-attachments/assets/c90c7460-4ce7-4c8d-b5ab-498ee77c86c6

**Comment by AlexanderNeumann** [comment]
The userinfo should be accessible if the authentication expects the `openid` scope. Regarding the last screen recording it seems to work, right?

**Comment by fwild** [comment]
Changes implemented as discussed, @cawke

**Review by cawke — APPROVED** [review]

**Pull request merged**
