### PR TITLE
Image Target Manager

### LINKED ISSUE #1296: Remove Vuforia from mobile platforms

### PR DESCRIPTION
**Pull request by cawke**
You can access the `ImageTargetManager` through `RootObject.Instance.imageTargetManager`.

Wrapper for three implementations: 
- `ImageTargetManagerARFoundation` - ARFoundation (Android, iOS)
- `ImageTargetManagerVuforia` - (Windows, Android, iOS) [currently conflicts with MRTK on Android, iOS, Editor, but should work on Hololens]
- `ImageTargetManagerEditor` - (Editor)

ImageTarget can be added from the editor to the `images` field or programmatically at runtime.

`public class ImageTargetModel` – a model that describes the ImageTarget:
- `public string name;` – name 
- `public Texture2D texture2D;` – texture
- `public float width = 1f;` – width
- `public GameObject prefab;` – a prefab that will be displayed when the object is tracked
- `public bool useLimitedTracking;` – when enabled, the object will not disappear in situations where the image is not tracked, but its position can be predicted.

image

- `public async Task<IImageTarget> AddImageTarget(ImageTargetModel model, CancellationToken cancellationToken = default)` – an asynchronous method for adding a new ImageTarget. If the ImageTarget cannot be created, the method will return null. For Editor and Vuforia, `IImageTarget` will be created immediately, but for ARFoundation, `IImageTarget` will only be created when the camera is pointed at the image (a feature of ARFoundation). If you need to cancel the creation of ImageTarget, you can use `cancellationToken`.
- `public void RemoveImageTarget(IImageTarget imageTarget)` – a method for removing ImageTarget. ARFoundation does not have an API for removing ImageTarget from the MutableRuntimeReferenceImageLibrary, but calling `RemoveImageTarget` will remove the prefab, simulating the removal of ImageTarget.

image

### CODE REVIEW

**Comment by cawke** [comment]
Also some unused scripts have been removed or fixed

**Comment by cawke** [comment]
it also removes the use of Vuforia from the mobile version.

**Comment by cawke** [comment]
https://github.com/WEKIT-ECS/MIRAGE-XR/wiki/ImageTargetManager

**Review by fwild — APPROVED** [review]

**Comment by fwild** [comment]
Tests, however, fail:

<test-case id="1130" name="CreateObject_ParentNameDoesNotExist_ReturnsNull" fullname="Tests.PlayerUtilitiesTests.CreateObject_ParentNameDoesNotExist_ReturnsNull" methodname="CreateObject_ParentNameDoesNotExist_ReturnsNull" classname="Tests.PlayerUtilitiesTests" runstate="Runnable" seed="950948677" result="Passed" start-time="2023-04-06 10:13:39Z" end-time="2023-04-06 10:13:39Z" duration="0.017138" asserts="0">
2023-04-06T10:14:28.9008944Z             <properties />
2023-04-06T10:14:28.9009548Z             <output><![CDATA[<color=#FF0000>[ERROR]</color> System.ArgumentException: Object this parent does not exist not found.
2023-04-06T10:14:28.9010275Z   at MirageXR.Utilities.CreateObject (System.String id, System.String parent) [0x00015] in /github/workspace/Assets/MirageXR/Player/Scripts/Utilities/Utilities.cs:145 
2023-04-06T10:14:28.9010566Z ]]></output>
2023-04-06T10:14:28.9010864Z           </test-case>

**Pull request merged**
