### PR TITLE
Updated to Unity 2021.3.8

### LINKED ISSUE #1031: Migrate develop to 2021
Since we had to update to a newer 2020 LTS version for AR foundation / AR core, we should go through with the 2021 update. Choose latest stable LTS version to update to (there might be a new one coming out today). Update code, check if anything breaks, and merge on develop.

### PR DESCRIPTION
**Pull request by BenediktHensen**
Closes #1031.

This pull request updates to Unity 2021.3.8. For this update, a couple of packages like the MRTK were also updated.

The Unity update comes with performance improvements in the editor, fixes the crash that happens when opening browser windows using Application.OpenURL and allows us to apply a configurable ruleset file for Stylecop.

### CODE REVIEW

**Comment by cawke** [comment]
@BenediktHensen I got this error
image

**Comment by fwild** [comment]
Anyone know why this is stuck?

**Comment by fwild** [comment]
I can see that develop is now updated to 2020.3.38f1, but this pull request is still hanging here. I can see that there are only two changes to .cs files: they are about orientation (changing to landscape orientation left) - I guess these have been done on the develop branch already, and this pull request can be stashed?

**Comment by BenediktHensen** [comment]
> @BenediktHensen I got this error image

Hm strange, I do not get this error on my installation and do not seem to be able to reproduce it.
However, in the update process, Unity has modified this dll in some way, so maybe that broke it and I might still be working on some cached version in the Library folder. I have now re-imported the NuGet for Unity package. Could you try again to see if it works now?

**Comment by cawke** [comment]
> > @BenediktHensen I got this error image
> 
> Hm strange, I do not get this error on my installation and do not seem to be able to reproduce it. However, in the update process, Unity has modified this dll in some way, so maybe that broke it and I might still be working on some cached version in the Library folder. I have now re-imported the NuGet for Unity package. Could you try again to see if it works now?

@BenediktHensen There is no error on the macbook. I do not have access to my PC, I can not check, but I think all is well. Please resolve the conflicts and you can merge. Thank you.

**Review by cawke — APPROVED** [review]
ty

**Comment by fwild** [comment]
FYI, when importing on my mac the freshly cloned git repo, I got the following consent confirmation dialogue:
image
I assume others will get the same, and maybe this resolves the issues with the pipeline as well...

**Pull request merged**
