### PR TITLE
1387 add captions to image augmentation

### PR DESCRIPTION
**Pull request by shidende**
The branch added captions to image and video augmentations

### CODE REVIEW

**Review by fwild — CHANGES_REQUESTED** [review]
There are a lot of files changed, that you actually did not touch - some of these seem to reintroduce files we removed already from develop (must have happened, because you branched off develop earlier).

Proposal: checkout a new develop branch; and manually copy all changed files over, check it if it still all works, and then push a new commit (with new branch name); and then add a new pull request.

**Comment by fwild** [comment]
I will leave this open until the new request is in!

**Comment by fwild** [comment]
This one is reworked now - closing.

**Comment by shidende** [comment]
Hi @Robert Hillman and @Fridolin Wild, should I wait for the new caption/alt attribute or proceed with captioning the video augmentation, and the two (video + image) will be fixed together. I assume all augmentations that need captioning will use the same attribute for captions.

**Pull request closed without merging**
