### PR TITLE
Hotfixes for version 2

### PR DESCRIPTION
**Pull request by robhillman97**
Closes; 
#1111 
#1110 
#1108 
#1105 
#1104 

back to activity
Navigation buttons

### CODE REVIEW

**Review by cawke — CHANGES_REQUESTED** [review]
Follow the code style.

**Comment by fwild** [comment]
@robhillman97 @cawke I think this one follows the code style (now)? Can you please check?

**Comment by robhillman97** [comment]
also closes #1118

**Review by cawke — APPROVED** [review]
ty

**Comment by cawke** [comment]
@robhillman97 Doesn't work on certain resolutions
image

**Pull request merged**
