### PR TITLE
Dynamic help view

### LINKED ISSUE #964: Implement dynamic HelpView
Context help via the (i) button in the button bar:

Screenshot 2022-06-16 at 15 06 38

With the context help depicted on the right implemented using the tutorial manager.

### PR DESCRIPTION
**Pull request by robhillman97**
Adds the help view.

closes #964

### CODE REVIEW

**Review by cawke — CHANGES_REQUESTED** [review]
Follow the code style.
After that I will look at the code in more detail

**Comment by fwild** [comment]
Can we approve this? So we can test? I agree with reworking it a little, and agree that the variable names should be fixed first - but if there are bigger changes (more event driven processing, e.g.), then we should do them after - so we can already engage in testing this new feature, which most certainly will yield some additional changes (at least to the help texts!)

**Review by cawke — APPROVED** [review]

**Review by cawke — CHANGES_REQUESTED** [review]
image

what Activity (21/11/2022 11:49:33) and others?

**Comment by cawke** [comment]
image

**Comment by cawke** [comment]
image

**Comment by cawke** [comment]
image

**Comment by cawke** [comment]
image

**Comment by cawke** [comment]
image

**Comment by cawke** [comment]
image

**Comment by cawke** [comment]
please test on different resolutions

**Comment by fwild** [comment]
I am sure this help view will have some additional things to resolve - but we cannot inspect it if we cannot test it. Can, @robhillman97 can you please build a test build (android)? And @cawke maybe we could please have this on ipad, too?

**Comment by robhillman97** [comment]
@fwild there is an APK here;
https://drive.google.com/drive/folders/1U_VQ2UF6DszvKkUZJhY3F01cEbsYVBC9?usp=sharing

**Comment by fwild** [comment]
@robhillman97 - how far are you away from finalising this pull request? Using Alex's refactored tutorial manager?

**Comment by robhillman97** [comment]
I haven't made changes to this branch since the last commit. The functionality of the dynamic help works here but using the old tutorial style. I was under the impression that the new method is to be implemented by Boris, so I am not really sure where that leaves this branch now. If we're using the new manager for dynamic help it would probably be best to scrap this branch, create a new branch from made from "ashubin/Tutorial" and start again.

**Comment by fwild** [comment]
@robhillman97 can you please check with Boris - and maybe help him, if he cannot do it for the xmas release in time? Might be an idea to merge this PR into the tutorial branch on which Boris is working now?

**Pull request closed without merging**
