### PR TITLE
Update models library UI

### PR DESCRIPTION
**Pull request by Alvareon**
Screenshot 2024-04-06 at 15 28 07
Screenshot 2024-04-06 at 15 30 35
Screenshot 2024-04-06 at 15 31 20

### CODE REVIEW

**Review by fwild — APPROVED** [review]

**Review by cawke — CHANGES_REQUESTED** [review]
doesn't match the design.

image

image

**Comment by cawke** [comment]
image

**Comment by Alvareon** [comment]
@cawke fixed.
 - added backgrounds;
 - scroll alignment;
Screenshot 2024-04-09 at 01 43 22

**Comment by cawke** [comment]
> @cawke fixed.
> 
> * added backgrounds;
> * scroll alignment;
> 
> Screenshot 2024-04-09 at 01 43 22

please add left margin for text

**Comment by Alvareon** [comment]
@cawke , increased the left margin a little bit
Screenshot 2024-04-09 at 12 41 16

**Review by cawke — APPROVED** [review]

**Pull request merged**
