### PR TITLE
Tested and Fixed image caption

### PR DESCRIPTION
**Pull request by shidende**
Hi, this pull request is fixing the image caption. See attached video

https://github.com/WEKIT-ECS/MIRAGE-XR/assets/88036240/ab09caf1-08c8-4113-a036-7e072aa87f55

### CODE REVIEW

**Comment by fwild** [comment]
implements #1783

**Review by cawke — DISMISSED** [review]
I see that some of the changes were included in the PR by accident. Roll them back.

image

**Comment by cawke** [comment]
@fominykh can you check from the video how much this solution matches the design in figma?

**Comment by fominykh** [comment]
@cawke and @shidende , we designed captions for Screen space only for mobile devices only.
The current implementation is (a) for smart glasses and (b) in world space. I think we can keep it as it is for now. We can design the captions for smart glasses and for world space later and update the visual appearance of captions.

**Comment by fwild** [comment]
The workflow changes are because Deogratias pulled from master - but these changes are ok, so I am putting it through. I have instructed him to in the future make sure he branches a fresh branch of develop, to avoid getting PRs handed back.

**Pull request merged**
