### PR TITLE
 Add virtual instructor

### PR DESCRIPTION
**Pull request by AKissmehl**
This PR introduces several new prefabs needed for the scenes of the virtual instructor editor.

### CODE REVIEW

**Review by fwild — APPROVED** [review]
Looks good to me, but would be good if Sergey glimpses over this as well!

**Comment by AKissmehl** [comment]
I indeed ask him rn. There is also one small thing missing where I need a references or tutorial. So there will be an update anyway soon.

**Comment by Alvareon** [comment]
@AKissMail if you plan to implement these panels as pop-ups, then these panels need to be removed from the main prefab: 

Screenshot 2024-10-15 192044

**Comment by Alvareon** [comment]
VISettings.prefab height does not match the height of the panel in Figma (251 vs 220)

**Pull request merged**
