### PR TITLE
Implementing audio captions

### PR DESCRIPTION
**Pull request by shidende**
This PR implements the audio caption. 
Please take a look at PR 1935. 
It has taken care of the requested changes and resolved the merge conflicts.

### CODE REVIEW

**Comment by fwild** [comment]
Still shows up here as "Merge conflict" - can you resolve this, please?

**Comment by cawke** [comment]
@shidende  let's first merge your past PR_1935 before checking this one. To do this, you need to fix conflicts in it.

**Comment by cawke** [comment]
@shidende Is [PR-1935](https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1935/files) identical to this? If so, is it possible to close this PR?

**Comment by fwild** [comment]
Seems equal to the PR we already merged. Closing.

**Pull request closed without merging**
