### PR TITLE
add scrollbar vertical to the Home Screen

### PR DESCRIPTION
**Pull request by Alvareon**
Screenshot 2024-04-07 at 01 04 22

### CODE REVIEW

**Review by fwild — APPROVED** [review]

**Comment by cawke** [comment]
@fominykh can you confirm the changes in design?

I think the white translucent line on the right is unnecessary.

image

**Comment by fominykh** [comment]
The semi-transparent line behind the slider is not needed. Sorry, this was a bug in the design. There is no line. See this screen (or design in Figma):
image

**Review by cawke — CHANGES_REQUESTED** [review]
based on comments

**Comment by Alvareon** [comment]
@cawke @fominykh Fixed

**Review by cawke — APPROVED** [review]

**Pull request merged**
