### PR TITLE
new action editor view was dropped from Content.prefab

### PR DESCRIPTION
**Pull request by fwild**
thus breaking the add augmentation menu, instead the old glyph editor view was linked...?

### CODE REVIEW

**Review by cawke — COMMENTED** [review]
All references to editors in the develop branch are correct, but it is strange that references to TMP_InpufField are missing. Didn't you have this error?

image

**Comment by fwild** [comment]
Just pulled your merge, and when I check now, both TMP input fields show up as correctly set.

But: Shouldn't element 3 be "action editor v2 (action editor view)"?

**Comment by fwild** [comment]
Weirdly enough, for me, if I leave element 3 as "GlyphEditor (Glyph Editor View)" and then start the app, the Content gameObject under Start / View / MobileUI_v2 / Pages / Content / Activity View / Panel / Content" will have element 3 empty, thus throwing an error when I try to bring up the 'add augmentation' menu.

**Comment by cawke** [comment]
> Just pulled your merge, and when I check now, both TMP input fields show up as correctly set.

I updated Text Mesh Pro and everything is fixed.

> But: Shouldn't element 3 be "action editor v2 (action editor view)"?

Yes, you're right, there's a mistake.

**Review by cawke — APPROVED** [review]

**Pull request merged**
