### PR TITLE
Tutorial

### PR DESCRIPTION
**Pull request by cawke**
a self-contained tutorial that does not interfere with the working code.

tutor_

To specify which button to select (copy) in the tutorial, use the TutorialItem class
**id** to determine which button to copy
**interactableObject** - link to Button or Toggle
**isPartOfScrollView** - if part of the scroll - so that the scroll will automatically move up
image

The tutorial queue can be saved in json if it is long.
**id** to determine which button to copy
**message** to be displayed in the window
**position**  - top, mid or bot
```
    public void ShowHelpView()
    {
        var queue = new Queue<TutorialModel>();
        queue.Enqueue(new TutorialModel { id = "tutorial_1_1", message = "1 message" });
        queue.Enqueue(new TutorialModel { id = "tutorial_1_2", message = "2 message", position = TutorialModel.MessagePosition.Bottom });
        queue.Enqueue(new TutorialModel { id = "tutorial_1_3", message = "3 message", position = TutorialModel.MessagePosition.Top });

        _tutorial.Show(queue);
        //PopupsViewer.Instance.Show(_helpPrefab);
    }
```

works with situations where there is no button yet. The tutorial will wait for it to appear.
```
    private async Task<TutorialItem> FindTutorialItem(string id)
    {
        for (int i = 0; i < MAX_TRY_COUNT; i++)
        {
            foreach (var searchRoot in _searchRoots)
            {
                var items = searchRoot.GetComponentsInChildren<TutorialItem>();
                if (items == null)
                {
                    continue;
                }

                var item = items.FirstOrDefault(t => t.id == id);
                if (item)
                {
                    return item;
                }
            }

            await Task.Delay(WAIT_IN_MILLISECONDS);
        }

        return null;
    }
```

It will also track the movement of the original button.
```
    private void SetUpCopy(TutorialItem item, TutorialItem copy)
    {
        if (item.button)
        {
            copy.button.onClick.RemoveAllListeners();
            copy.button.onClick.AddListener(() => OnCopyClicked(item, copy));
        }

        if (item.toggle)
        {
            copy.toggle.onValueChanged.RemoveAllListeners();
            copy.toggle.onValueChanged.AddListener(value => OnCopyClicked(item, copy));
        }

        copy.StartTracking(item.transform);
    }
```

@BorisJov  What needs to be done: 
fill in the queues for the Tutorial.
show the pop-up help window. it depends on the current screen.
it is possible to add that the message window would automatically select a position so as not to overlap the button (optional)

If you have any questions or if you find a bug or issue, post it here

### CODE REVIEW

**Comment by BorisJov** [comment]
I think its best if I continue work on this branch. Can we make the PR a draft?

**Comment by fwild** [comment]
I moved the documentation to its own wiki page:
https://github.com/WEKIT-ECS/MIRAGE-XR/wiki/TutorialManager-dialogue-system

**Comment by cawke** [comment]
@BorisJov  @robhillman97 

I'm the only one with this bug with missing links? I rolled back everything, but the links still did not appear.
image

**Comment by BorisJov** [comment]
It works ok for me.

**Pull request merged**
