### PR TITLE
Hololens fixes

### PR DESCRIPTION
**Pull request by BorisJov**
Fixing issue where tutorial wouldn't advance, also fixes issue #1412

### CODE REVIEW

**Comment by BorisJov** [comment]
@cawke Not sure which branch to merge into, please change if required

**Review by fwild — APPROVED** [review]
merge into hololens fix branch?

**Comment by BorisJov** [comment]
@robhillman97 @cawke @fwild I suggest we first merge develop or release_2.2 into the HololensFix branch before merging this one in, to avoid the merge conflicts

**Comment by robhillman97** [comment]
Fixed conflicts, merging into Hololens fix

**Pull request merged**
