### PR TITLE
Create new search screen

### PR DESCRIPTION
**Pull request by Alvareon**
Result:

search

### CODE REVIEW

**Review by cawke — CHANGES_REQUESTED** [review]
remove space 

image

**Comment by Alvareon** [comment]
done

**Review by cawke — CHANGES_REQUESTED** [review]
The scroll view is larger than the view and the bottom elements are not visible

image

**Comment by Alvareon** [comment]
> The scroll view is larger than the view and the bottom elements are not visible
> 
> image

fixed

**Review by cawke — APPROVED** [review]

**Pull request merged**
