### PR TITLE
Universal Rendering Pipeline

### LINKED ISSUE #1785: Update to Universal Rendering Pipeline
Carefully check esp. glTFast support (3D model augmentation)

### PR DESCRIPTION
**Pull request by BenediktHensen**
Closes #1785.

This pull request changes the project from the built-in rendering pipeline to the Universal Rendering Pipeline (URP). It also initializes the rendering settings. Materials and particle effects were adjusted or remade so that they are compatible with the URP. In the MRTK, the option was activated that the MRTK standard shader now also uses URP.

### CODE REVIEW

**Review by fwild — APPROVED** [review]

**Review by cawke — CHANGES_REQUESTED** [review]
the camera rendering order is broken

**Comment by fwild** [comment]
@cawke does it work for you now? I have experienced no issues, and I am keen to progress with the lighting ticket (which depends on URP)

**Comment by fwild** [comment]
The last push from me resolves https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1939, https://github.com/WEKIT-ECS/MIRAGE-XR/issues/1406, and https://github.com/WEKIT-ECS/MIRAGE-XR/issues/845

**Comment by cawke** [comment]
fix https://github.com/WEKIT-ECS/MIRAGE-XR/pull/1944

**Pull request merged**
